spring:
  datasource:
    url: jdbc:mysql://60.205.1.227:3306/exammanage?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 30
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 4MB
      max-request-size: 4MB

server:
  port: 8080 # 修改内置Tomcat的端口号

# Mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.exam.entity # 别名扫描
  configuration:
    map-underscore-to-camel-case: true # 开启全局驼峰映射，即将数据库形如student_id的字段映射到实体类的属性studentId上。

logging:
  level:
    com.example.exam.controller: debug
    com.example.exam.dao: debug
    com.example.exam.service: debug
